### ISSUE TITLE
Error when a transaction has no remittanceInformation

### ISSUE THREAD

**Issue by pivoj** [VitexSoftware/abraflexi-raiffeisenbank#1]
When no reference or code is provided with the transaction, the "remittanceInformation" block is not present at all. (Which is different behavior to e.g. "references", where an empty block is used instead.)

remittanceInformation existance should be tested before https://github.com/VitexSoftware/abraflexi-raiffeisenbank/blob/4efcb4b5582e1651b9957aac14099a0a0594332d/src/AbraFlexi/RaiffeisenBank/Transactor.php#L95

PHP Warning:  Undefined property: stdClass::$remittanceInformation in /usr/share/abraflexi-raiffeisenbank/RaiffeisenBank/Transactor.php on line 96
PHP Fatal error:  Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /usr/share/abraflexi-raiffeisenbank/RaiffeisenBank/Transactor.php:96

**Comment by Vitexus** [comment]
Thank you for reporting this issue. It will fixed.
